global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"



scrape_configs:
  - job_name: 'my-flask-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['flask-app:5000']